version: '3'
services:
  flask:
    build: .
    command: gunicorn -b 0.0.0.0:5000 hello:app --reload
    environment:
        - FLASK_APP=hello.py
        - FLASK_DEBUG=1
        - PYTHONUNBUFFFERED=True
    ports: 
        - '5000:5000'
    volumes: 
        - ./:/root